# docker-compose.yml
version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: spotify-postgres
    environment:
      POSTGRES_USER: spotifyuser
      POSTGRES_PASSWORD: spotifypassword
      POSTGRES_DB: spotifydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: