spring:
  application:
    name: spotify-ai-poc
  datasource:
    url: jdbc:postgresql://localhost:5432/spotifydb
    username: spotifyuser
    password: spotifypassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
